### ISSUE TITLE
noisy warning messages about Dataset variance

### ISSUE THREAD

**Issue by kartiksubbarao** [Lumiwealth/quantstats_lumi#15]
Sometimes with small datasets, _sns.kdeplot() will complain `UserWarning: Dataset has 0 variance`. This doesn't really add value as it's obvious from the quantstats charts, and it just adds to noise in log files. There is a simple option to turn that off: `warn_singular=False`. I'll submit a pull request for that, it would be great if we can silence these noises :-)

**Comment by kartiksubbarao** [comment]
Thanks @grzesir, appreciate your stewardship of this project!

**Comment by grzesir** [comment]
> Thanks @grzesir, appreciate your stewardship of this project!

@kartiksubbarao No problem. Not sure why the original author abandoned it, but I'm a huge fan and we use it a lot in our library, lumibot. If you haven't seen our library yet, I think you'll really like it.
