### ISSUE TITLE
axis/graph formatting issues in 0.3.1 when setting y-axis limits

### ISSUE THREAD

**Issue by kartiksubbarao** [Lumiwealth/quantstats_lumi#42]
There was a recent patch in 0.3.1 that explicitly set y-axis limits to returns.min() and returns.max(), to remove a small blank "buffer" area of the graphs. While this works fine for some returns, there are other returns where this truncates the graph and/or prevents the lowest y-axis label from being displayed. My recommendation would be to revert this particular part of the patch, since it appears that matplotlib seems to need that buffer area. Here are some illustrations:

version 0.3.0 -- notice how the -15% label is present as the lowest y-axis label:
![image](https://github.com/Lumiwealth/quantstats_lumi/assets/134209/547f9e73-4903-432a-9e93-b2fb29fc0425)

version 0.3.1 -- the -15% label is missing:
![image](https://github.com/Lumiwealth/quantstats_lumi/assets/134209/caa77549-4f95-43d8-8a27-b5b3ca1b8952)

another example:

version 0.3.0 -- the lowest axis label is -2% and the graph is clear:

![image](https://github.com/Lumiwealth/quantstats_lumi/assets/134209/d9418b4d-66cb-47d3-b1ff-c407f7839637)

version 0.3.1 -- the -2% label is missing, and the graph's lowest datapoints are truncated:

![image](https://github.com/Lumiwealth/quantstats_lumi/assets/134209/8180a841-bb09-4de1-895d-3ccb84a490f1)

**Comment by hygarlic** [comment]
This has been fixed in 0.3.2. 

Ticket can be closed.
